name: Build Release Packages

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  GO_VERSION: '1.21'

jobs:
  # 使用原有的 build-release.sh 脚本构建标准包
  build-standard:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Initialize Go module
      run: |
        if [ ! -f go.mod ]; then
          go mod init github.com/ffay/lanproxy-go-client
          go mod tidy
        fi

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y upx-ucl

    - name: Run original build script
      run: |
        chmod +x build-release.sh
        ./build-release.sh

    - name: Upload standard artifacts
      uses: actions/upload-artifact@v4
      with:
        name: standard-packages
        path: |
          *.tar.gz
          client_*
        retention-days: 30

  # 专门为 OpenWrt 构建 IPK 包
  build-openwrt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # 基于原脚本的架构，添加 OpenWrt 特定配置
          - name: mips
            goos: linux
            goarch: mips
            gomips: softfloat
            target: mips_24kc
          - name: mipsel
            goos: linux
            goarch: mipsle
            gomips: softfloat
            target: mipsel_24kc
          - name: arm7
            goos: linux
            goarch: arm
            goarm: "7"
            target: arm_cortex-a7
          - name: ipq60xx
            goos: linux
            goarch: arm
            goarm: "7"
            target: ipq60xx

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Initialize Go module
      run: |
        if [ ! -f go.mod ]; then
          go mod init github.com/ffay/lanproxy-go-client
          go mod tidy
        fi

    - name: Build OpenWrt binary
      env:
        CGO_ENABLED: 0
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        GOARM: ${{ matrix.goarm }}
        GOMIPS: ${{ matrix.gomips }}
      run: |
        VERSION=$(date -u +%Y%m%d)
        if [ "${{ github.ref_type }}" == "tag" ]; then
          VERSION=${{ github.ref_name }}
        fi
        
        LDFLAGS="-X main.VERSION=$VERSION -s -w"
        
        # 使用与原脚本相同的命名规则
        OUTPUT_NAME="client_linux_${{ matrix.name }}"
        
        go build -ldflags "$LDFLAGS" -o $OUTPUT_NAME ./src/main
        
        # 压缩二进制文件
        if command -v upx >/dev/null 2>&1; then
          upx -9 $OUTPUT_NAME || true
        fi

    - name: Create simple OpenWrt package
      run: |
        VERSION=$(date -u +%Y%m%d)
        if [ "${{ github.ref_type }}" == "tag" ]; then
          VERSION=${{ github.ref_name }}
        fi
        
        BINARY_NAME="client_linux_${{ matrix.name }}"
        PACKAGE_NAME="lanproxy-client-${{ matrix.target }}-$VERSION"
        
        # 创建简单的目录结构
        mkdir -p $PACKAGE_NAME/usr/bin
        mkdir -p $PACKAGE_NAME/etc/init.d
        
        # 复制二进制文件
        cp $BINARY_NAME $PACKAGE_NAME/usr/bin/lanproxy-client
        
        # 创建简单的启动脚本
        cat > $PACKAGE_NAME/etc/init.d/lanproxy << 'EOF'
#!/bin/sh /etc/rc.common
START=99
STOP=10
PROG=/usr/bin/lanproxy-client

start() {
    start-stop-daemon -S -q -p /var/run/lanproxy.pid -m -b -x $PROG -- -s "$SERVER_HOST" -p "$SERVER_PORT" -k "$CLIENT_KEY"
}

stop() {
    start-stop-daemon -K -q -p /var/run/lanproxy.pid
    rm -f /var/run/lanproxy.pid
}
EOF
        
        chmod +x $PACKAGE_NAME/etc/init.d/lanproxy
        
        # 打包为 tar.gz
        tar -czf $PACKAGE_NAME.tar.gz $PACKAGE_NAME/
        
        # 生成校验和
        sha256sum $PACKAGE_NAME.tar.gz > $PACKAGE_NAME.tar.gz.sha256
        md5sum $PACKAGE_NAME.tar.gz > $PACKAGE_NAME.tar.gz.md5

    - name: Upload OpenWrt artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-${{ matrix.target }}
        path: |
          *.tar.gz
          *.sha256
          *.md5
          client_linux_*
        retention-days: 30

  release:
    needs: [build-standard, build-openwrt]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Prepare release files
      run: |
        mkdir -p release
        
        # 复制所有文件到发布目录
        find artifacts -type f \( -name "*.tar.gz" -o -name "*.sha256" -o -name "*.md5" -o -name "client_*" \) -exec cp {} release/ \;
        
        # 创建发布说明
        cat > release/README.md << 'EOF'
# LanProxy Go Client Release

## 标准发布包
- `lanproxy-client-*-*.tar.gz` - 模仿原始 build-release.sh 的构建结果
- `client_*` - 直接可执行的二进制文件

## OpenWrt 专用包
- `lanproxy-client-*-*.tar.gz` - 适用于 OpenWrt 路由器的包

## 使用方法

### 标准平台
```bash
# 解压并运行
tar -xzf lanproxy-client-*.tar.gz
./client_* -s SERVER_IP -p SERVER_PORT -k CLIENT_KEY
```

### OpenWrt 路由器
```bash
# 上传到路由器
scp client_linux_* root@192.168.1.1:/usr/bin/lanproxy-client

# 设置权限并运行
ssh root@192.168.1.1 "chmod +x /usr/bin/lanproxy-client"
ssh root@192.168.1.1 "/usr/bin/lanproxy-client -s SERVER_IP -p 4900 -k CLIENT_KEY"
```

## 架构说明
- `mips_24kc` - MIPS 路由器（Atheros、MediaTek等）
- `mipsel_24kc` - Little-endian MIPS 路由器
- `arm_cortex-a7` - ARM 路由器（包括大部分现代路由器）
- `ipq60xx` - Redmi AX5 等 IPQ60xx 芯片路由器
EOF

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
        body_path: release/README.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}